services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: hairhealth-postgres
    environment:
      - POSTGRES_DB=hairhealth
      - POSTGRES_USER=hairhealth_user
      - POSTGRES_PASSWORD=hairhealth_dev_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hairhealth_user -d hairhealth"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: